leftnav:
- identifier: e7e768f4-1c08-1d5e-301f-6500469295c5
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 1f4bedc3-8c07-7047-78e5-1833440f8dad
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 016c6954-5a7a-2c0e-7161-8063a7cd7ea1
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 54b83455-a0e0-1617-033f-e3cac6d343dc
  name: Lecture Slides
  url: /pages/lecture-slides
  weight: 40
- identifier: 2b6fe43e-289d-188d-c3ad-2bd2ffde82d3
  name: Assignments
  url: /pages/assignments
  weight: 50
- identifier: 892558e1-8f59-8f17-b49f-52929b201ad9
  name: Projects
  url: /pages/projects
  weight: 60
